# Generated by Django 3.2.18 on 2023-08-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homeAddress',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='workAddress',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
